### ISSUE TITLE
目录可以合并一下

### ISSUE THREAD

**Issue by moxiaonai** [IceEnd/Yosoro#1]
感觉两个目录栏目可以合并成一个目录树，两栏太占地方了，13.5寸的本打开，编辑区域没多少了

**Comment by IceEnd** [comment]
默认情况下应用大小是 1180 * 786，markdown编辑区域的占比只比50%多一点，这个编辑体验的确不好，后续再做改进。

目前如果感觉编辑不方便，可以拉宽应用，或者点击右上角的模式切换按钮，隐藏笔记栏目框。

**Comment by pixcai** [comment]
界面设计感觉可以参考有道云笔记，现在默认的1200宽度对笔记本来说确实太大了。

**Comment by IceEnd** [comment]
#103
