### ISSUE TITLE
添加个图床怎么样？

### ISSUE THREAD

**Issue by beldon** [IceEnd/Yosoro#10]
如题，写markdown会有时候需要用到图片，能不能添加一些图床呢？图床可以考虑用github仓库或者gitee仓库等等

**Comment by IceEnd** [comment]
计划先加上七牛，不过业余时间有限，要等一段时间。

**Comment by inkydragon** [comment]
不如用现有的项目 https://github.com/Molunerfinn/PicGo

**Comment by lartpang** [comment]
若是可以利用微博作为图床，那应该会方便很多

**Comment by IceEnd** [comment]
现在加上了Github仓库作为图床，其他平台后续追加。

https://github.com/IceEnd/Yosoro/wiki/Image-Hosting

**Comment by LiliCache** [comment]
> 若是可以利用微博作为图床，那应该会方便很多

顶，希望添加微博图床，国内响应速度飞快

**Comment by IceEnd** [comment]
@LiliCache 后面有计划再支持几个图床和本地图库，或者云盘图库。
