### ISSUE TITLE
Open project... Add existing... Open all folders inside yosoro documents...

### ISSUE THREAD

**Issue by raojala** [IceEnd/Yosoro#100]
**Is your feature request related to a problem? Please describe.**
I can't seem to find a way to open existing markdown files or add existing files to a project.

**Describe the solution you'd like**
Moving existing markdown folders that adhere to folder model to a project directory, shows them as projects inside Yosoro. This way, when folder is renamed outside yosoro it would still work.

**Additional context**
![image](https://user-images.githubusercontent.com/12243682/54439281-2888a180-4741-11e9-8efb-7b15193af59a.png)

**Comment by IceEnd** [comment]
Due to design ills, yosoro does not read the data under the folder(documents), but stores it in `localstorage`, so it will not take effect when moving files directly.

I will add an "Import" option to the menu bar to let you import files and folders.

**Comment by IceEnd** [comment]
#103
