### ISSUE TITLE
图片上传异常

### ISSUE THREAD

**Issue by lishang6257** [IceEnd/Yosoro#110]
**Describe the bug**
当拖拽图片到note，提示（Image upload failedPlease check the network or configuration），但是PC网络正常，onedrive同步也正常

**Screenshots**
![Snipaste_2019-04-19_10-07-01](https://user-images.githubusercontent.com/26080906/56401661-8eaa9c00-628c-11e9-9b9c-c4587cf1913e.png)

**Desktop (please complete the following information):**
 - OS: [win10 1809]

**Comment by IceEnd** [comment]
图床都配置的吗？在设置里面有相应的配置。

**Comment by lishang6257** [comment]
十分感谢，已解决！推荐在readme里提供显眼wiki链接。感谢！


| |
lishang6257
|
|
lishang6257@163.com
|
签名由网易邮箱大师定制
在2019年4月19日 10:32，Alchemy<notifications@github.com> 写道：

图床都配置的吗？在设置里面有相应的配置。
