### ISSUE TITLE
建议添加类似typora的即时渲染功能

### ISSUE THREAD

**Issue by dreambuildor** [IceEnd/Yosoro#117]
在设置中可以选择模式，一种是现在这样的带编辑框和预览框的编辑模式，另一种是类似typora的即时渲染编辑模式，特别喜欢typora的这种模式，所以我觉得这个软件要是也有这个功能就特别完美啦。感谢作者！

**Comment by IceEnd** [comment]
已经注入Muya

**Comment by dreambuildor** [comment]
哈哈哈哈太强了你，谢谢大神！
