### ISSUE TITLE
取消导出文件报错

### ISSUE THREAD

**Issue by leiyuanxi** [IceEnd/Yosoro#12]
** 描述bug **
取消导出.md或者.html文件报错

** 复现步骤 **
1、点击导出.md或者.html
2、点击导出界面的取消按钮
3、验证是否会出现报错

** 修复建议 **
点击取消，不会导出文件，并且不会出现报错

** 相关截图 **
![image](https://user-images.githubusercontent.com/29453569/40462141-3d2bdf82-5f41-11e8-8872-9c3d45243b8e.png)

** 操作系统 **
机器：MAC mini
OS：macOS High Sierra 10.13.4

**Comment by IceEnd** [comment]
你好，这个bug 会在 [v1.0.5](https://github.com/IceEnd/Yosoro/projects/4#card-10019510) 修复，感谢支持。
