### ISSUE TITLE
Failed to read file data无法读取文件数据

### ISSUE THREAD

**Issue by RenkoQ** [IceEnd/Yosoro#120]
问题：打开后空白，提示“Failed to read file data”。尝试从onedrive恢复，依然空白并显示提示。

应用版本为最新版，系统是 macos mojave 10.14.5

**Comment by IceEnd** [comment]
![image](https://user-images.githubusercontent.com/11556339/60780151-da742f80-a16f-11e9-9e27-19ca3980cb4e.png)
在设置里面可以看到笔记文件的保存路径，确认一下里面的`documents`下面是否有对应的文件。

**Comment by RenkoQ** [comment]
已解决 非常感谢！
