### ISSUE TITLE
建议缩小Note间距

### ISSUE THREAD

**Issue by leiyuanxi** [IceEnd/Yosoro#14]
建议缩小Note间距，如果多了，会不是很好找
同时建议增加整个文件夹同步，就不需要对每个Note

相关截图：
![image](https://user-images.githubusercontent.com/29453569/40776819-752afc20-64fe-11e8-990b-43fe3d6f7869.png)

PS：我是不是事儿真多😆

**Comment by IceEnd** [comment]
笔记的高度的空白是留给`笔记描述`（这个以后会自动截取笔记一部分当作概览）和`笔记标签`（目前还没做）。

同步整个文件夹在计划中。
