### ISSUE TITLE
能支持Latex数学公式吗？

### ISSUE THREAD

**Issue by JetSquirrel** [IceEnd/Yosoro#16]

**Comment by IceEnd** [comment]
后续追加

**Comment by IceEnd** [comment]
数学公式功能已完成，下个版本发布。

行内公式： $$x^2=y$$

块级公式：

$$
x^2=y
$$

![2018-09-29.10.17.27-image.png](https://raw.githubusercontent.com/IceEnd/Yosoro-Img/img/yosoro/2018-09-29.10.17.27-image.png)
