### ISSUE TITLE
编辑较大markdown文件的时候卡顿非常严重（2000行）。

### ISSUE THREAD

**Issue by Jsnows** [IceEnd/Yosoro#17]
后续会优化解析器性能吗？

**Comment by IceEnd** [comment]
针对大文件的编辑卡顿，考虑添加防抖，将编辑器替换成[monaco-editor](https://microsoft.github.io/monaco-editor/index.html)，其他方案待定。

**Comment by Jsnows** [comment]
不是编辑区造成的。是marked语法解析太慢还有就是dom渲染造成的阻塞，我看你的代码并没有添加缓存处理，每次都marked全量解析dom全量替换。有考虑重写一个markdown语法解析器吗？

**Comment by IceEnd** [comment]
不考虑重写`marked`，这方面的问题只考虑转换防抖与渲染页内容增量更新
