### ISSUE TITLE
增加普通格式的笔记

### ISSUE THREAD

**Issue by qrs101** [IceEnd/Yosoro#21]
非常简洁好用的笔记，提一点小问题。
目前只支持markdown笔记，能不能支持添加txt格式的笔记，此外希望能够自动同步所有笔记。

**Comment by IceEnd** [comment]
谢谢建议，目前还不考虑其他格式的笔记功能。

自动同步会涉及到多个终端的冲突问题，等想好解决方案会追加设置页面，增加“自动同步”按钮
