### ISSUE TITLE
分栏的bug

### ISSUE THREAD

**Issue by MagicLogic** [IceEnd/Yosoro#26]
**Describe the bug**
分栏为两个，或一个时，搜索失败后，分栏按钮不展示了。导致无法查看笔记本导航。需重启软件才行。

**To Reproduce**
1. 点击分栏按钮，让分栏为两个或一个
2. 搜索框搜索
3. 主界面空白，分栏按钮消失，无法查看笔记。只能重启

**Comment by IceEnd** [comment]
能留下版本号与操作系统吗，我再macOS和win7下测试都是正常的。

**Comment by MagicLogic** [comment]
版本：1.0.6
OS：win10  1709 
![image](https://user-images.githubusercontent.com/22311672/41951421-77ebf950-79fd-11e8-900d-63c0237160f1.png)
搜索框应该是搜索笔记本的。当点击如图按钮，到以下模式时。搜索内容会出现主界面空白现象，无法继续操作
![image](https://user-images.githubusercontent.com/22311672/41951460-9b8ec37e-79fd-11e8-8ae5-15b8c973d96b.png)
![image](https://user-images.githubusercontent.com/22311672/41951521-de607404-79fd-11e8-867f-5743e442ec7f.png)

**Comment by IceEnd** [comment]
好的，重现了。
