### ISSUE TITLE
打开多个桌面，原有笔记本消失

### ISSUE THREAD

**Issue by Azureki** [IceEnd/Yosoro#29]
win10系统，已经打开了yosoro。（但我忘了，于是在另一个桌面又打开，发现什么都没有。）
打开笔记本文件夹，笔记全都在。
在yosoro中又新建原来的笔记本（名字是一样的），结果笔记本文件夹消失，回收站中没有。

**请问要怎么恢复笔记？**

**Comment by IceEnd** [comment]
暂时不要同时打开两个桌面，文件列表存放在`localstorage`中，这块逻辑可能有点问题，同时打开多个桌面时，意外将列表清空了。

不过文件还在，windows10路径是 c盘下的：`C:\Users\xxx\%AppData%/Roaming\Yosoro/documents/projects/`，xxx是用户名，你可以把文件复制出来。
如果上传到了OneDrive，直接下载即可。

我会做一些尝试改进，如果仍然有问题，会将数据放进`indexedDB`中或者文件中存储。

**Comment by Azureki** [comment]
@IceEnd 感谢回复~不过这个我已经知道了。我知道在另一个桌面打开，原来的文件还在。

> 打开笔记本文件夹，笔记全都在。

我的问题是：
> 在新打开的yosoro中又新建原来的笔记本（名字是一样的），结果笔记本文件夹消失。

我在资源管理器中看不到了……

**Comment by IceEnd** [comment]
@Azureki 新建目录，我没有对文件夹是否存在进行校验，`fs`模块直接擦除了原有的文件夹，这是个bug。

所以文件恢复不了，不好意思。

**Comment by Azureki** [comment]
好的，我知道了。
