### ISSUE TITLE
重命名笔记 会生成两个笔记文件

### ISSUE THREAD

**Issue by Azureki** [IceEnd/Yosoro#30]
执行以下步骤可以复现：
1. 新建一个笔记（比如test1），写点内容 （比如123）。
2. 重命名这个笔记（比如test12），再写点内容（比如456）。

这时候用资源管理器打开笔记本文件夹就会有**两个文件**。
并且都是**刚生成的**。两个文件中的内容也是一样的（123456）。

不知道这算不算feature……

----

**Comment by IceEnd** [comment]
这是个bug……感谢捉虫！
