### ISSUE TITLE
Can This Application support LaTeX ?

### ISSUE THREAD

**Issue by TerenceLiu98** [IceEnd/Yosoro#31]
Can This Application support LaTeX? Because sometimes we need to type mathematical formula in the  note. Maybe support Mathjax just like Typora, an another Markdown application.

**Comment by IceEnd** [comment]
I am currently investing time in the development of new editors(using `slate`), so I will not develop this feature for the time being, and I am not familiar with LaTeX.

**Comment by TerenceLiu98** [comment]
@IceEnd I see.
