### ISSUE TITLE
编辑界面样式改进

### ISSUE THREAD

**Issue by Celinaaaa** [IceEnd/Yosoro#32]
首先感谢这个作品！不管是窗口、logo还是小动画都非常的喜欢！

接着是一点小建议：个人审美下，觉得编辑文字的界面与周围界面比较违和（就是不太符合我的审美）。希望能早日出一些自定义功能，自己设定编辑界面的字体、大小等等，预览界面也可以选择用自己喜欢的CSS

非常喜欢，谢谢作者～

**Comment by IceEnd** [comment]
谢谢。现在正在重写编辑器，DIY的功能以后会加上去。
