### ISSUE TITLE
文章无法删除和重命名

### ISSUE THREAD

**Issue by lovese** [IceEnd/Yosoro#33]
![image](https://user-images.githubusercontent.com/13268438/42858464-588caebc-8a81-11e8-8675-c1fcce8e6c18.png)
![image](https://user-images.githubusercontent.com/13268438/42858487-717515fe-8a81-11e8-9910-6c04d5432a0f.png)
![image](https://user-images.githubusercontent.com/13268438/42858495-7ee54812-8a81-11e8-8571-a96f34bb87dd.png)
也无法同步，就这一篇文章这样，难道是因为文章标题使用了双引号？？？

**Comment by IceEnd** [comment]
你好，麻烦将步骤简单的描述一下，我稍后将尝试一下。

现阶段解决方法：将文件内容复制，进入到文件目录，删除该文件，回到应用上删除列表中的项目。不同系统可能对文件名称有限制，我没有加上校验文件名合法性，可能使这块导致的bug。

**Comment by lovese** [comment]
我就是新建文章，然后复制了标题和正文内容，接着upload提示失败，我又新建一篇文章，标题自己写，内容直接复制和上一篇一样的，然后upload就没问题，但是原来那篇居然删不了，也不能改名字，所以我认为应该是标题的问题，标题带了双引号和冒号，至于你说的删除该文件，我不知道怎么删，因为没有upload成功，所以云上没有该文件，但是本地的文件我找不到，不懂怎么删除该文件

**Comment by IceEnd** [comment]
@lovese 文件保存在系统应用数据目录，windows下的路径为：`C:\Users\xxx\AppData\Roaming\Yosoro\documents\projects`，`xxx`是你的用户名。

我会尽快解决这个问题。

**Comment by lovese** [comment]
@IceEnd 
![image](https://user-images.githubusercontent.com/13268438/42866044-086ddd62-8a9e-11e8-8f49-9131408de13b.png)
![image](https://user-images.githubusercontent.com/13268438/42866070-1ba18ed8-8a9e-11e8-919e-573a286f395c.png)
名字不一样
