### ISSUE TITLE
Incompatible module found when running yarn on Windows

### ISSUE THREAD

**Issue by Frederick-S** [IceEnd/Yosoro#34]
**Describe the bug**
`electron-installer-debian` is incompatible with Windows.

**To Reproduce**
1. Run `yarn` or `npm install`
2. See error

**Expected behavior**
All dependencies should be installed successfully.

**Screenshots**
<img width="780" alt="default" src="https://user-images.githubusercontent.com/1182395/43034290-919cc3b2-8d0c-11e8-8a65-9ce2f22e1e7e.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Comment by IceEnd** [comment]
Please try:

```yarn --ignore-platform```

**Comment by Frederick-S** [comment]
@IceEnd 
<img width="955" alt="default" src="https://user-images.githubusercontent.com/1182395/43034925-217f7dde-8d18-11e8-9504-f287db630245.PNG">

<img width="937" alt="2" src="https://user-images.githubusercontent.com/1182395/43034950-a1501e06-8d18-11e8-97d5-bbbebfa600de.PNG">

Thanks! But another error occurred, it seems it's a [known issue](https://github.com/LinusU/node-alias/issues/14) and not fixed.

**Comment by IceEnd** [comment]
From the output point of view, it should be that the module has not been installed. You also try the following method:

- Remove `node_modules` and try the installation again.

- Switch registry for `npm`, use `taobao`, or `cnpm`.

If it still doesn't work：

1. Remove `electron-installer-debian`(this is a linux package tool, not used on windows) from `package.json`.

<img width="441" alt="8d35f225-1bc1-49c3-9ec4-38e4603ca019" src="https://user-images.githubusercontent.com/11556339/43035186-96e25f9c-8d1d-11e8-8d8e-c14aa7667083.png">

2. Then run `yarn`.

**Comment by Frederick-S** [comment]
@IceEnd The second solution works, thanks!
