### ISSUE TITLE
Upload failed with Microsoft school/work account

### ISSUE THREAD

**Issue by Frederick-S** [IceEnd/Yosoro#35]
**Describe the bug**
Failed to upload note to OneDrive with Microsoft school/work account.

**To Reproduce**
1. Sign in with Microsoft school/work account
2. Click `New Note` and write something
3. Click upload

**Expected behavior**
It should upload successfully.

**Screenshots**
<img width="483" alt="default" src="https://user-images.githubusercontent.com/1182395/43036834-4e22def4-8d3a-11e8-8332-04823e5368d9.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Comment by IceEnd** [comment]
I will use a work account to do the test.

**Comment by IceEnd** [comment]
#28
