### ISSUE TITLE
分栏右侧滚动条能否按左侧滚动条百分比滚动

### ISSUE THREAD

**Issue by needal** [IceEnd/Yosoro#40]
左侧滚动条拉到底而右侧滚动条只会滚动部分 不能拉到底
必须使用右键点击 右侧才会滚动到对应位置

**Comment by IceEnd** [comment]
你好，能给一下操作系统吗？

视图同步有两种情况：

- 鼠标滚动，是根据滚动条的百分比进行同步的
- 编辑中，会根据光标的当前行数确定预览界面滚动条的位置

在我的机器上，是可以滚动到底的。

**Comment by needal** [comment]
我的是win10
![11](https://user-images.githubusercontent.com/24469784/43850788-7d22c108-9b6b-11e8-9704-26e4431fe182.gif)
右侧不会滚动到底

**Comment by IceEnd** [comment]
这一部分，编辑笔记时会根据光标所在的位置（光标行数/总行数），确定右边的定位。

如果是直接滚动鼠标，是可以滚到底部的，当你把光标切到最后一行，右边的也会滚动到最底下。

根据光标所在行数定位，我感觉有些问题，后续版本会给个设置选项，控制是否开启。
