### ISSUE TITLE
improve PDF view

### ISSUE THREAD

**Issue by ripertn** [IceEnd/Yosoro#43]
First of all, **thanks a lot** for this wonderful mark down editor. I have been using it for 1 month now, and so far, it rocks !

I would like to point out 2 features that would be a nice to have:
 - **first feature** : currently, a link (link pointing on a part of the document itself, useful in tab of contents for example) that I add in a markdown document, does not work in the pdf view. I have to export the pdf. It is only in this case that it works. **it would be cool for link from a tab of content to work in the pdf view of yosoro**

This is the kind of link I am speaking of:

![feature_request](https://user-images.githubusercontent.com/36069116/43958989-80b0f892-9cad-11e8-885c-270607ab4d14.png)

when I click on "1 setting environment", yosoro should show me the paragraph with the html balise correspondig. curently, it does not.

- **second feature** : I dont know if the problem comes from yosoro. It might come from my pdf reader, but still I tell you just in case:
when a I add a long line of code, using the type of markdown below, it is impossible to scroll through it (horizontally) in the pdf I export. I can scroll horizontally through it in Yosoro pdf view, but not in the exported pdf:

    IO.puts("this is a long line of code that will be impossible to scroll through horizontally, once the pdf is exported... however, maybe it is pdf's reader fault, I should do some more test to pin down my doubts")

Thank you for reading me, I hope I was clear enough and it was not too confusing. Tell me if such suggestions are not welcomed, or if it helps you.

**Comment by IceEnd** [comment]
@ripertn Thanks very much.

The first feature I will improve in the near future.

The second function, I need some time to investigate and fix.

**Comment by ripertn** [comment]
Hi @IceEnd I downloaded latest version, and I am delighted to see you have added the first feature in the latest versions.

I just wanted to say **thank you again**, and you can count on me to point out new stuff if I see any.
