### ISSUE TITLE
Add option for non Medium user

### ISSUE THREAD

**Issue by ntsd** [IceEnd/Yosoro#46]
I think I'll add an option for non Medium user to hide or disable the export button when medium auth isn't config

I think it needs to change a part of UI

maybe turn settings menu like this

![untitled](https://user-images.githubusercontent.com/8283616/44075033-5ab8d07c-9fc5-11e8-9a3a-c23f3453c23d.png)

**Comment by IceEnd** [comment]
This's great.

**Comment by IceEnd** [comment]
I have modified the UI, like this:

![image](https://user-images.githubusercontent.com/11556339/44155581-43ee81fe-a0e0-11e8-8201-6562bdb0ac42.png)

**Comment by ntsd** [comment]
Sorry for late, I'm looking for job now. I'll do it later.
