### ISSUE TITLE
notebook&note是否能拖动以更换顺序

### ISSUE THREAD

**Issue by yuianch** [IceEnd/Yosoro#59]
以及Windows平台下支持快速切换布局模式（快捷键？），目前需切换三次回到初始布局
thanks

**Comment by IceEnd** [comment]
拖拽排序在计划中，下个版本修改了一下布局模式的切换，如图
![image](https://user-images.githubusercontent.com/11556339/45998479-98dd3100-c0d5-11e8-9de9-0c229d62c840.png)
布局菜单栏选项和快捷键，会慢慢加上。
