### ISSUE TITLE
[help]怎么使用xcode编译呢？

### ISSUE THREAD

**Issue by csanycall** [IceEnd/Yosoro#6]
我才转到macos，只会用xcode，貌似这个事html5？需要安装什么插件么？

另外，我想自己建立云端（替换OneDrive），需要注意哪些方面？

谢谢！

**Comment by IceEnd** [comment]
Yosoro基于`Electron`和`React`，我这边打包使用的是[electron-packager](https://github.com/electron-userland/electron-packager)，需要在Node.js环境执行：

```shell
npm run packager:mac
```

`Electron`提供的几种打包方式请参考：https://electronjs.org/docs/tutorial/application-distribution

关于其他云驱动：目前只接入了`oneDrive`提供的RESTFUL API，想用其他的平台就需要自己去扩展代码了。
