### ISSUE TITLE
本地文件存储在哪？

### ISSUE THREAD

**Issue by DariusG4** [IceEnd/Yosoro#7]
您好，请问这个软件的本地存储放在哪？
还有就是不知能不能上传一篇样式文档上来？还不太会格式，想参照着用。
感谢这个简洁好用的工具，谢谢。

**Comment by IceEnd** [comment]
本地的MarkDown存放在当前用户的应用数据文件夹，默认对应：

- `%APPDATA%` Windows 中
- `$XDG_CONFIG_HOME` or `~/.config` Linux 中
- `~/Library/Application Suppor`t macOS 中

对应数据文件夹中的`documents`文件夹，projects是笔记本，`trash`文件夹是废纸篓。

**Comment by DariusG4** [comment]
感谢回复，请问数据文件夹支不支持通过配置文件进行修改？如果可以修改的话，就可以将数据文件夹放进网盘中，就会好用很多。

**Comment by IceEnd** [comment]
不支持，笔记本和笔记的一些信息保存在`LocalStorage`中，暂时不支持导入。
