### ISSUE TITLE
add image description

### ISSUE THREAD

**Issue by SysuJayce** [IceEnd/Yosoro#75]
**Is your feature request related to a problem? Please describe.**
I have to add image description myself everytime I upload image to Github.  

I want something like this:
`![example.png](https://raw.githubusercontent.com/xxx/example.png "example")`

But right now Yosoro wont add description automatically. It just give me this:
`![example.png](https://raw.githubusercontent.com/xxx/example.png)`

**Describe the solution you'd like**
Can you give us an option whether the description of an image will be added automatically?  
If user choose to add description automatically, maybe we can simply use the image filename as the description.

Thank you!

**Comment by IceEnd** [comment]
![example.png](https://raw.githubusercontent.com/xxx/example.png)

[example.png] 不就是一个图片的描述吗？

**Comment by SysuJayce** [comment]
额，可能用词不当。我想说的是，将鼠标移到渲染后的图片上显示出来的描述，比如这种

![_20181027144054](https://user-images.githubusercontent.com/12313888/47600599-61281880-d9f6-11e8-9194-0a45d556f230.png)

**Comment by IceEnd** [comment]
不过这个与markdown的解析无关。

`![title](xxx.png)`，`title`即是这个图片的标题。你是想在预览界面增加一个图片的鼠标hover展示`title`的功能吗？

**Comment by SysuJayce** [comment]
是的

**Comment by IceEnd** [comment]
@SysuJayce OK

**Comment by SysuJayce** [comment]
因为只要在URI后面加上这个字符串就可以当鼠标hover在图片上面的时候展示出title，而当图片较多的时候这种功能可能还是需要的。

`![example.png](https://raw.githubusercontent.com/xxx/example.png "example")`

另外还有两个小建议，如有需要可以另外开一个issue。  
1. 能否优化预览和编辑界面的同步，在v1.1.1中发现预览会跟编辑界面存在较大不同步问题。
2. 当编辑界面滚动条拉到最下面的时候能不能继续下拉使得编辑器中最后一行位于屏幕靠近中间的位置，因为所编辑的行在屏幕中上部分比较舒适。我当前的做法是多打几十个换行来保证我编辑的最新一行是在屏幕中间，避免低头看屏幕下方。

**Comment by IceEnd** [comment]
@SysuJayce 反馈已收到，我会抽空做优化。

**Comment by IceEnd** [comment]
![image](https://user-images.githubusercontent.com/11556339/51665596-1b7beb80-1ff7-11e9-80be-4d31bda56728.png)

鼠标放置3s，title就会显示。

> 另外还有两个小建议，如有需要可以另外开一个issue。
> 
> 1. 能否优化预览和编辑界面的同步，在v1.1.1中发现预览会跟编辑界面存在较大不同步问题。
> 2. 当编辑界面滚动条拉到最下面的时候能不能继续下拉使得编辑器中最后一行位于屏幕靠近中间的位置，因为所编辑的行在屏幕中上部分比较舒适。我当前的做法是多打几十个换行来保证我编辑的最新一行是在屏幕中间，避免低头看屏幕下方。

第一个问题1.1.3已修复。

**Comment by IceEnd** [comment]
https://github.com/IceEnd/Yosoro/releases/tag/v1.1.5
