### ISSUE TITLE
PDF Layout Improvements

### ISSUE THREAD

**Issue by KelvinMcClean** [IceEnd/Yosoro#76]
I currently use this program to write notes on papers, which results in long sentences. When I convert my document to a PDF to share it, I notice that words are cut in half by the PDF converter.

It would be great if the PDF converted would have layout options, or try to only go to a new line on spaces, or on hyphon keys.

It would be great to have this feature. Thanks for your hard work.

**Comment by IceEnd** [comment]
@KelvinMcClean I will fix this problem :).

**Comment by KelvinMcClean** [comment]
The most recent release seems to solve the issue. Thanks!
