### ISSUE TITLE
导出的pdf是空白的

### ISSUE THREAD

**Issue by chenminicode** [IceEnd/Yosoro#77]
**Describe the bug**
导出的pdf是空白的

**To Reproduce**
1. Go to '导出pdf'

**Expected behavior**
导出有内容的pdf

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.1
 - Yosoro: 1.1.2

**Additional context**
1.1.1版本可以正常导出pdf

**Comment by IceEnd** [comment]
谢谢提醒，有问题版本已经下线，今晚会发布修复好的版本。
