### ISSUE TITLE
Failed to load resource: the server responded with a status of 503 (Service Unavailable)

### ISSUE THREAD

**Issue by xinjiayu** [IceEnd/Yosoro#78]
按说明安装后，无法启动。
出现提示logo后，不进入下一个页面。

![image](https://user-images.githubusercontent.com/5157534/48884815-0224ba80-ee61-11e8-80e6-1f07f4e666b9.png)

操作系统：macos 10.14.1

**Comment by IceEnd** [comment]
你启动渲染进程了吗？

```
npm run dev:renderer
```

渲染进程启动了，再command + R 刷新试试。

**Comment by xinjiayu** [comment]
启动渲染进程后，也是进不去的。

![image](https://user-images.githubusercontent.com/5157534/48886057-782b2080-ee65-11e8-9a83-e2f1ae3d37a7.png)

**Comment by IceEnd** [comment]
@xinjiayu 渲染进程编译有问题，建议删掉`node_modules`，重新安装试试。

看报错是`app/views/component/share/Notification.js`这个通知信息模块有问题，你可以打个断点看看哪里有问题。

**Comment by xinjiayu** [comment]
> @xinjiayu 渲染进程编译有问题，建议删掉`node_modules`，重新安装试试。
> 
> 看报错是`app/views/component/share/Notification.js`这个通知信息模块有问题，你可以打个断点看看哪里有问题。

node的版本有要求吗？

**Comment by xinjiayu** [comment]
OK了，把node全删除了，重新安装的，就可以了。谢谢。

**Comment by IceEnd** [comment]
@xinjiayu 👌
