### ISSUE TITLE
请问能添加一下基本语言的教程吗？

### ISSUE THREAD

**Issue by Love-in-August** [IceEnd/Yosoro#82]
请问能添加一下一些基本语言的命令吗，目前只学到了加粗和换行，求加一个基本操作的默认笔记，没学过编程但是很喜欢版主写的这个笔记软件，求采纳或者告知一下文档的基本命令，感觉没大小格式什么的自己记得一团糟。谢谢！

**Comment by IceEnd** [comment]
@Love-in-August 可以先看看 [markdown语法教程](https://www.appinn.com/markdown/)，这上面除了Latex数学公式，其他的语法都有。

后面也会加一些快捷的选项（标题、链接、图片...），如果还有其他意见，欢迎提出来。

**Comment by Love-in-August** [comment]
> 
> 
> @Love-in-August 可以先看看 [markdown语法教程](https://www.appinn.com/markdown/)，这上面除了Latex数学公式，其他的语法都有。
> 
> 后面也会加一些快捷的选项（标题、链接、图片...），如果还有其他意见，欢迎提出来。

非常感谢！

**Comment by Love-in-August** [comment]
> 
> 
> @Love-in-August 可以先看看 [markdown语法教程](https://www.appinn.com/markdown/)，这上面除了Latex数学公式，其他的语法都有。
> 
> 后面也会加一些快捷的选项（标题、链接、图片...），如果还有其他意见，欢迎提出来。

您好，不好意思再次打扰您，我想请问下我在设置图片结束后上传图片后，总是显示上传失败，在Yosoro的Image hosting中我Rep设置是计算机名/repo，Branch设置的是git的用户名，Token设置的是token界面生成的项目名称（一行代码），Path我没有设置，请问是哪里设置有问题吗？

**Comment by IceEnd** [comment]
你要先创建一个图片仓库。
![image](https://user-images.githubusercontent.com/11556339/49579861-6a5abc80-f988-11e8-9911-d751870277ca.png)

- repo：用户名/仓库名
- branch：默认 master

**Comment by Love-in-August** [comment]
> 
> 
> 你要先创建一个图片仓库。
> ![image](https://user-images.githubusercontent.com/11556339/49579861-6a5abc80-f988-11e8-9911-d751870277ca.png)
> 
>     * repo：用户名/仓库名
> 
>     * branch：默认 master

已经整理好，感谢指导！
