### ISSUE TITLE
macos下在编辑状态command+z后文档内容被下面的文档覆盖无法恢复！

### ISSUE THREAD

**Issue by Fixerrrrrr** [IceEnd/Yosoro#87]
![image](https://user-images.githubusercontent.com/17157334/50507611-2ce5dc80-0ab9-11e9-9fc1-9d9f1790a7bd.png)
在当前状态下command+z后，内容被2中的内容覆盖。
![image](https://user-images.githubusercontent.com/17157334/50507661-64548900-0ab9-11e9-9ad8-29edc3725ea8.png)

**Comment by IceEnd** [comment]
感谢抓虫，bug已修复，下个版本发布。
