### ISSUE TITLE
希望上传图片的时候异步

### ISSUE THREAD

**Issue by henta** [IceEnd/Yosoro#93]
现在上传图片，就卡住了，不能继续写东西，特别是用github作为仓库的时候，本来就慢，卡的很难受，希望能把上传图片做成异步，这样就可以在上传图片的时候继续工作了！

**Comment by IceEnd** [comment]
这一点会做优化

**Comment by Azimiao** [comment]
> 
> 
> 这一点会做优化

给大佬递茶🍮
