### ISSUE TITLE
编辑行过长显示错误

### ISSUE THREAD

**Issue by BlueFlyMing** [IceEnd/Yosoro#96]
最近才发现这个编辑器，相当好用，但是使用过程中也遇到了一些问题：
1. 当编辑 标题 时，行过长会显示错误
![20190215234417-image.png](https://raw.githubusercontent.com/BlueFlyMing/file/master/img/20190215234417-image.png)
2. 每次关闭后再打开都是默认位置、大小，不是上次编辑时的状态，希望能改善一下，谢谢
3. 希望能加个页面搜索功能，类似vscode的 ctrl+f

**Comment by IceEnd** [comment]
问题会尽快解决
