### ISSUE TITLE
Graphs, diagrams and such..

### ISSUE THREAD

**Issue by raojala** [IceEnd/Yosoro#97]
**Describe the solution you'd like**
I would like to make diagrams and flowcharts using ```sequence or flow. similar to typora. Is that planned or has something similar already been implemented?

![image](https://user-images.githubusercontent.com/12243682/53285716-80e50880-376c-11e9-9f55-7b3626ee13cc.png)

Markdown mermdaid support might do the trick? https://mermaidjs.github.io/

**Comment by raojala** [comment]
#91 is same request if google translate translate is right.

**Comment by IceEnd** [comment]
Thanks, I will add this feature.
